### PR TITLE
Add tests for rewriting headers and status.

### PR DESCRIPTION
**Pull request by ryanlovett**

### CODE REVIEW

**Comment by maresb** [comment]
Ah, bad timing, we simultaneously duplicated each others efforts.

**Comment by maresb** [comment]
I forgot to add `orig_response` to the signature in my test case...

**Comment by maresb** [comment]
I think my tests cover the same as your tests, but slightly more. Anything you think I should add?

**Comment by ryanlovett** [comment]
No worries, it looks good to me. Thanks!

**Pull request closed without merging**
